POST http://localhost:3000/login
Content-Type: application/json

{
    "username":"Soo",
    "password":"123456"
}

###分割线
GET http://localhost:3000/bye

###
GET http://localhost:3000

###
POST http://localhost:3000/register
Content-Type: application/jason

{
    "username":"Jia Xuen",
    "password":"112233",
    "name":"XhawnGG",
    "email":"GG@hotmail.com"
}