POST http://localhost:3000/login
Content-Type: application/json

{
    "username":"Soo",
    "password":"123456"
}

###分割线
GET http://localhost:3000/bye

###
GET http://localhost:3000

###
//127.0.0.1
POST http://localhost:3000/register
Content-Type: application/jason

{
    "username":"Jia Xuen",
    "password":"112233",
    "name":"XhawnGG",
    "email":"GG@hotmail.com"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username":"Soo",
    "password":"123456"
}

###

GET http://localhost:3000/bye
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNvbyIsInBhc3N3b3JkIjoiMTIzNDU2IiwibmFtZSI6IllvdSBHdWFuIiwiZW1haWwiOiJTb29Zb3VHdWFuQGdhbWlsLmNvbSIsImlhdCI6MTY4NTQ3MTY4MywiZXhwIjoxNjg1NDgxNjgzfQ.RA0voSgskxfFDzmk4mgR6pb54-u0XmXfl2xyOehAarM